### ISSUE TITLE
socket failed: EPERM (Operation not permitted)

### ISSUE THREAD

**Issue by Eng-AhmedShehata** [stipop-development/stipop-android-sdk#3]
Process: com.hana, PID: 24759
    java.net.SocketException: socket failed: EPERM (Operation not permitted)
        at java.net.Socket.createImpl(Socket.java:492)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at io.stipop.APIClient$Companion$get$1.invoke(APIClient.kt:57)
        at io.stipop.APIClient$Companion$get$1.invoke(APIClient.kt:36)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
2021-09-03 18:10:03.914 24759-24832/com.hana I/Process: Sending signal. PID: 24759 SIG: 9

**Comment by hojunjeong90** [comment]
Did you allow **internet permission in AndroidManifest.xml** file?

`<uses-permission android:name="android.permission.INTERNET"/>`

And try running the app again after **Build > Clean Project**.

**Comment by Eng-AhmedShehata** [comment]
Yes, I did that but still crash (same error).
This problem shows in Android studio emulators and in real devices if there is no internet connection.

**Comment by hojunjeong90** [comment]
@Eng-AhmedShehata 

https://stackoverflow.com/questions/56266801/java-net-socketexception-socket-failed-eperm-operation-not-permitted

`Delete and reinstall the app on your device or emulator.`

This link may also help you solve the problem. If this is not the case, additional reports are required. T^T

**Comment by Eng-AhmedShehata** [comment]
Thank you bro.
This solution solved my problem.
